### ISSUE TITLE
Issues with restarting mirror and MMM-Dimmer changing parameters

### ISSUE THREAD

**Issue by Nneuland** [kolbyjack/MMM-Dimmer#2]
HI there,

I've probably been entered incorrect parameters into this module, but I'm having some frustrating issues.
I've been messing with different numbers and seem to get further and further away from what I'm trying to accomplish.
Also when saving an unchanged config file, the mirror dims or brightens with no change to the code.  Weird.

I was hoping you could help me with a 4 hour dim time after sunset.  TransitionDuration settings and sunsetTransitionOffset?

Any help would be greatly appreciated.

Nick

**Comment by kolbyjack** [comment]
Do you mean you want the screen to take four hours to dim, starting at sunset, or you want it to start dimming four hours after sunset?

Start to dim at sunset, finish dimming four hours later (and unfortunately, since I don't have separate config items to control how quickly the screen dims vs how quickly it brightens, this will also take four hours to brighten at sunrise):
```
{
  module: "MMM-Dimmer",
  position: "fullscreen_above",
  config: {
    transitionDuration: 4 * 60 * 60 * 1000,
  }
}
```

Start to dim four hours after sunset, and take the default fifteen minutes to dim:
```
{
  module: "MMM-Dimmer",
  position: "fullscreen_above",
  config: {
    sunsetTransitionOffset: 4 * 60 * 60 * 1000,
  }
}
```

**Comment by Nneuland** [comment]
Thank you!  Yes.  'm looking to dim starting at sunset.  So if sunset is at 2000, with 4 hours to dim completely, at 2400 the screen will be at full dim.  So it's either using  transitionDuration OR sunsetTransitionOffset.  I'll have to try these parameters tonight.

Thank you kindly

**Comment by kolbyjack** [comment]
You can use them together if you want, they just control different things.  I've also added separate settings for `sunriseTransitionDuration` and `sunsetTransitionDuration` if you don't want to also start brightening the screen four hours before sunrise.

**Comment by Nneuland** [comment]
This was exactly the issue.  Thank you so much.

**Comment by Nneuland** [comment]
Hi there,

I thought I had it, but still having issues.  

With these settings, I'm finding the mirror dim very quickly after sunset.  Not taking a gradual 4 hours to dim{
  module: "MMM-Dimmer",
  position: "fullscreen_above",
  config: {
    transitionDuration: 4 * 60 * 60 * 1000,
  }
}
And with this set up, I'm not noticing dimming at all
{
  module: "MMM-Dimmer",
  position: "fullscreen_above",
  config: {
    sunsetTransitionOffset: 4 * 60 * 60 * 1000,
  }
}

It seems easy enough.  Bright until sunset , then gradual dim over 4 hour period.  sunriseTransitionOffset could be a different parameter, say
 1 * 60 * 60 * 1000, for brighten within 1 hour from sunrise.  i think

I'm wondering how to use sunsetTransitionDuration, sunriseTransitionDuration, and transitionDuration together to achieve this.

If you have time to explain for my smooth brain.  Thank you

**Comment by kolbyjack** [comment]
Sorry about this, I thought I'd fixed the issue with it dimming/brightening quickly.  I have mine using the default 15 minute timeout, so I usually don't even notice if it's working quite right because I'm not looking at it during that time.

The `Offset` values adjust the time when the module thinks the sun is rising or setting.  The `Duration` values tell it how quickly to brighten/dim once the sun rises/sets.  So you should only need to use the `Duration` values:

```js
{
  module: "MMM-Dimmer",
  position: "fullscreen_above",
  config: {
    sunriseTransitionDuration: 1 * 60 * 60 * 1000,
    sunsetTransitionDuration: 4 * 60 * 60 * 1000,
  }
}
```

If it's still not working, I'll add some debug logging to see if we can capture some logs to find out what's going on.

**Comment by Nneuland** [comment]
Thanks Jackman.

It's slow with trouble shooting for me.  Need to monitor. I'll try this tonight.

I've noticed though, that if I adjust anything during the transition period in the config file, (say the mirror isn't dimming at all and I make an adjustment to the config file maxdim change for example) the mirror dims dramatically.  But doesnt stick for the following day.  not sure this makes sense

**Comment by kolbyjack** [comment]
ah, that may be it, then.  When the module starts up, it doesn't attempt to find the correct current dimming value and then continue dimming from there, it just sets the current dim value to whatever the full bright/dim value will be for the next transition.  Since my dimming durations were so short, that was sufficient for me.  I'll see if I can make the startup state handle being in the middle of a transition more elegantly.

**Comment by Nneuland** [comment]
That’d be great.  Looking forward to hearing back !  Thank you

**Comment by kolbyjack** [comment]
Ok, it seems that transitioning the opacity is more problematic than transitioning the background color, which can include opacity.  Try latest and let me know if it works for you.

**Comment by Nneuland** [comment]
Oh wow, you're quick.  Thanks for the tweak.  I've updated, and will let
you know how it goes.

Thanks so much Jon

Nick

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Nneuland** [comment]
Hey there.
Despite your update I'm still noticing some issues.  Perhaps I've modified by config file incorrectly.  I would love if you could take a look at how I have my conig file is set up.

{
			module: "MMM-PiTemp",
		    position: "top_right",
		    disabled: false,
		    config: {}
		},
		{
			module: "MMM-Dimmer",
			position: "fullscreen_above",
			config: { // See "Configuration options" for more information.
			  longitude: 40.650002,
			  latitude: -73.949997,
			  maxDim: 0.7,
			  transitionDuration: 3 * 60 * 60 * 1000,
		  }
		},
		{
		    module: 'MMM-nyc-transit',

Maybe there is something very obvious I'm missing.

I'm using this module in conjunction with the MMM-Remote module.  Perhaps this is the issue?

After first updating this module I was at full brightness.  Once I disable, then enable the module via the remote module, it sets my brightness very low.  Very dim, before the sunset time has started.  Any suggestions?

**Comment by kolbyjack** [comment]
aha!  Your latitude and longitude are swapped. Right now, it thinks you're in Antarctica!

**Comment by Nneuland** [comment]
OHHHH man.  Thank you.  I have no business here!  ha.  Thank you.

I'll let you know how that goes

**Comment by Nneuland** [comment]
We’ll… despite changing the coordinates, I’m running into the same issues for this long dim. [full bright until modifying the config file, or disabling then enabling dimmer module via MMM-Remote]  I appreciate all of your help.  If you think of any other cause for this issue, please let me know.  Seems to be no rhyme or reason
